FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    poppler-utils \
    cairo-dev \
    giflib-dev \
    libjpeg-turbo-dev \
    pango-dev \
    musl-dev \
    && npm install --production

COPY package*.json ./

RUN npm install --production

COPY . .

CMD ["node", "workers/AIProcessor.js"]