FROM node:20-alpine

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    libcairo-dev \
    libjpeg-turbo-dev \
    pango-dev \
    giflib-dev \
    cairo-dev

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5000

CMD ["npm", "start"]